from . import help
from . import start
from . import salom
from . import informatika_uchun
from . import abiturentlar_uchun
from . import ingliz_tili_uchun
from . import menu_uchun
from . import As_men_qaytish_uchun
from . import inline_abiturentlar_uchun
from . import media
from . import online_murojat
from . import echo